# 免费节点来源

sources:

  - name: sunmiao
    url: "https://sunmiao4458.github.io/free-proxy-airport/clash.yaml"
    format: clash
    enabled: true

  - name: au1rxx
    url: "https://github.com/Au1rxx/free-vpn-subscriptions/raw/main/output/clash.yaml"
    format: clash
    enabled: true

  - name: thordata
    url: "https://thordata.github.io/awesome-free-proxy-list/data/clash/all.yaml"
    format: clash
    enabled: true
