name: Fetch Free Node Sources

on:
  workflow_dispatch:

jobs:
  fetch-sources:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch and inspect sources
        run: |
          python src/fetch_sources.py

      - name: Merge and deduplicate nodes
        run: |
          python src/merge_nodes.py

      - name: Download Mihomo
        run: |
          mkdir -p bin

          curl -fL \
            -o bin/mihomo.gz \
            https://github.com/MetaCubeX/mihomo/releases/download/v1.19.31/mihomo-linux-amd64-v3-v1.19.31.gz

          gunzip -f bin/mihomo.gz
          chmod +x bin/mihomo

          ./bin/mihomo -v

      - name: Test one node
        run: |
          python src/test_one_node.py
